name: equinox_flood
description: Equinox — AI-powered flood prediction & river monitoring for India.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  http: ^1.2.1
  connectivity_plus: ^6.0.3
  intl: ^0.19.0
  fl_chart: ^0.68.0
  flutter_local_notifications: ^17.1.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  cached_network_image: ^3.3.1
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  lottie: ^3.1.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.2
  cupertino_icons: ^1.0.8
  workmanager: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  flutter_launcher_icons: ^0.14.1

# App icon config — run: flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0A1628"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"

flutter:
  uses-material-design: true
  # Uncomment each line below only after creating the folder locally:
  # assets:
  #   - assets/icon/
  #   - assets/images/
  #   - assets/animations/
