// lib/services/export_service.dart
// Generates PDF and CSV exports of flood data.

import 'dart:io';
import 'package:csv/csv.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

class ExportService {
  ExportService._();
  static final instance = ExportService._();

  // ─ PDF ────────────────────────────────────────────────────────────────────
  Future<File> generatePdf({
    required String title,
    required List<Map<String, dynamic>> rows,
    List<String>? columns,
  }) async {
    final doc = pw.Document();
    final cols = columns ?? (rows.isNotEmpty ? rows.first.keys.toList() : <String>[]);

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (ctx) => [
          pw.Header(
            level: 0,
            child: pw.Text(
              title,
              style: pw.TextStyle(
                fontSize: 20,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.white,       // was: white70 (does not exist)
              ),
            ),
          ),
          pw.SizedBox(height: 12),
          pw.Table.fromTextArray(
            headers: cols,
            data: rows.map((r) => cols.map((c) => '${r[c] ?? ''}').toList()).toList(),
            headerStyle: pw.TextStyle(
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.white,
            ),
            headerDecoration: const pw.BoxDecoration(color: PdfColors.blueGrey700),
            cellStyle: const pw.TextStyle(fontSize: 10),
            cellAlignments: {for (var i = 0; i < cols.length; i++) i: pw.Alignment.centerLeft},
          ),
          pw.SizedBox(height: 8),
          pw.Text(
            'Generated by OpsFlood • ${DateTime.now().toIso8601String()}',
            style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey),
          ),
        ],
      ),
    );

    final dir  = await getApplicationDocumentsDirectory();
    final file = File('${dir.path}/opsflood_export_${DateTime.now().millisecondsSinceEpoch}.pdf');
    await file.writeAsBytes(await doc.save());
    return file;
  }

  // ─ CSV ────────────────────────────────────────────────────────────────────
  Future<File> generateCsv({
    required String title,
    required List<Map<String, dynamic>> rows,
    List<String>? columns,
  }) async {
    final cols = columns ?? (rows.isNotEmpty ? rows.first.keys.toList() : <String>[]);
    final data = [
      cols,
      ...rows.map((r) => cols.map((c) => r[c] ?? '').toList()),
    ];
    final csv  = const ListToCsvConverter().convert(data);
    final dir  = await getApplicationDocumentsDirectory();
    final file = File('${dir.path}/opsflood_export_${DateTime.now().millisecondsSinceEpoch}.csv');
    await file.writeAsString(csv);
    return file;
  }
}
