// lib/services/export_service.dart
// Generates PDF and CSV exports of flood data.

import 'dart:io';
import 'package:csv/csv.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';
import '../services/alert_engine.dart';

// ── ExportRow ──────────────────────────────────────────────────────────────────────
/// Holds a single station’s data for export (CSV or PDF).
class ExportRow {
  final String          stationName;
  final String          river;
  final String          district;
  final double          currentLevel;
  final double          dangerLevel;
  final double          warningLevel;
  final double          hfl;
  final AlertSeverity?  severity;
  final DateTime        observedAt;

  const ExportRow({
    required this.stationName,
    required this.river,
    required this.district,
    required this.currentLevel,
    required this.dangerLevel,
    required this.warningLevel,
    required this.hfl,
    required this.observedAt,
    this.severity,
  });

  Map<String, dynamic> toMap() => {
    'Station':       stationName,
    'River':         river,
    'District':      district,
    'Current (m)':   currentLevel.toStringAsFixed(2),
    'Warning (m)':   warningLevel.toStringAsFixed(2),
    'Danger (m)':    dangerLevel.toStringAsFixed(2),
    'HFL (m)':       hfl.toStringAsFixed(2),
    'Severity':      severity?.label ?? 'NORMAL',
    'Observed At':   observedAt.toIso8601String(),
  };
}

// ── ExportService ──────────────────────────────────────────────────────────────
class ExportService {
  ExportService._();
  static final instance = ExportService._();

  // ─ PDF ─────────────────────────────────────────────────────────────────────
  Future<File> generatePdf({
    required String title,
    required List<Map<String, dynamic>> rows,
    List<String>? columns,
  }) async {
    final doc  = pw.Document();
    final cols = columns ?? (rows.isNotEmpty ? rows.first.keys.toList() : <String>[]);

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (ctx) => [
          pw.Header(
            level: 0,
            child: pw.Text(
              title,
              style: pw.TextStyle(
                fontSize: 20,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.white,
              ),
            ),
          ),
          pw.SizedBox(height: 12),
          pw.Table.fromTextArray(
            headers: cols,
            data: rows.map((r) => cols.map((c) => '${r[c] ?? ''}').toList()).toList(),
            headerStyle: pw.TextStyle(
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.white,
            ),
            headerDecoration:
                const pw.BoxDecoration(color: PdfColors.blueGrey700),
            cellStyle: const pw.TextStyle(fontSize: 10),
            cellAlignments: {
              for (var i = 0; i < cols.length; i++)
                i: pw.Alignment.centerLeft
            },
          ),
          pw.SizedBox(height: 8),
          pw.Text(
            'Generated by OpsFlood • ${DateTime.now().toIso8601String()}',
            style:
                const pw.TextStyle(fontSize: 8, color: PdfColors.grey),
          ),
        ],
      ),
    );

    final dir  = await getApplicationDocumentsDirectory();
    final file = File(
        '${dir.path}/opsflood_export_${DateTime.now().millisecondsSinceEpoch}.pdf');
    await file.writeAsBytes(await doc.save());
    return file;
  }

  // ─ CSV ─────────────────────────────────────────────────────────────────────
  Future<File> generateCsv({
    required String title,
    required List<Map<String, dynamic>> rows,
    List<String>? columns,
  }) async {
    final cols = columns ??
        (rows.isNotEmpty ? rows.first.keys.toList() : <String>[]);
    final data = [
      cols,
      ...rows.map((r) => cols.map((c) => r[c] ?? '').toList()),
    ];
    final csv  = const ListToCsvConverter().convert(data);
    final dir  = await getApplicationDocumentsDirectory();
    final file = File(
        '${dir.path}/opsflood_export_${DateTime.now().millisecondsSinceEpoch}.csv');
    await file.writeAsString(csv);
    return file;
  }

  // ─ High-level helpers used by ExportScreen ─────────────────────────────

  /// Builds a CSV file from [rows] and opens the OS share-sheet.
  /// Returns the saved file path.
  Future<String> exportAndShareCsv(List<ExportRow> rows) async {
    final maps  = rows.map((r) => r.toMap()).toList();
    final file  = await generateCsv(
      title:   'OpsFlood Export',
      rows:    maps,
    );
    await Share.shareXFiles(
      [XFile(file.path, mimeType: 'text/csv')],
      subject: 'OpsFlood CSV Export',
    );
    return file.path;
  }

  /// Builds a PDF file from [rows] and opens the OS share-sheet.
  /// Returns the saved file path.
  Future<String> exportAndSharePdf(
    List<ExportRow> rows, {
    String? reportTitle,
  }) async {
    final maps  = rows.map((r) => r.toMap()).toList();
    final title = reportTitle ?? 'OpsFlood Flood Report';
    final file  = await generatePdf(title: title, rows: maps);
    await Share.shareXFiles(
      [XFile(file.path, mimeType: 'application/pdf')],
      subject: title,
    );
    return file.path;
  }
}
