// Equinox Flood — Firebase Cloud Messaging (FCM) Service
import 'dart:async';
import 'dart:convert';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';

import '../constants.dart';
// ignore: uri_does_not_exist — generated by flutterfire configure
import '../firebase_options.dart';

class FcmFloodAlert {
  final String city;
  final String state;
  final String severity;
  final String river;
  final double currentLevel;
  final double dangerLevel;
  final String message;
  final DateTime receivedAt;

  const FcmFloodAlert({
    required this.city,
    required this.state,
    required this.severity,
    required this.river,
    required this.currentLevel,
    required this.dangerLevel,
    required this.message,
    required this.receivedAt,
  });

  factory FcmFloodAlert.fromMap(Map<String, dynamic> data) {
    double sf(dynamic v) =>
        v == null ? 0.0 : (double.tryParse(v.toString()) ?? 0.0);
    return FcmFloodAlert(
      city:         (data['city']          ?? data['location'] ?? 'Unknown').toString(),
      state:        (data['state']         ?? '').toString(),
      severity:     (data['severity']      ?? 'HIGH').toString().toUpperCase(),
      river:        (data['river']         ?? data['river_name'] ?? '').toString(),
      currentLevel: sf(data['current_level'] ?? data['river_level']),
      dangerLevel:  sf(data['danger_level']),
      message:      (data['message']       ?? data['body'] ?? '').toString(),
      receivedAt:   DateTime.now(),
    );
  }
}

// Background handler runs in a separate isolate — must be top-level.
@pragma('vm:entry-point')
Future<void> _fcmBackgroundHandler(RemoteMessage message) async {
  // FIX: guard against duplicate-app error when isolate already has Firebase.
  if (Firebase.apps.isEmpty) {
    await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  }
  if (kDebugMode) debugPrint('[FCM-BG] ${message.data}');
}

class FcmService {
  FcmService._();
  static final FcmService instance = FcmService._();

  static const _tokenKey = 'equinox_fcm_token';

  final _alertController = StreamController<FcmFloodAlert>.broadcast();
  Stream<FcmFloodAlert> get alertStream => _alertController.stream;

  String? _token;
  String? get token => _token;

  bool _initialized = false;

  Future<void> init() async {
    if (_initialized) return;
    _initialized = true;

    try {
      // FIX: guard against duplicate-app — Firebase may already be initialized
      // by firebase_messaging background handler or by main.dart indirectly.
      if (Firebase.apps.isEmpty) {
        await Firebase.initializeApp(
          options: DefaultFirebaseOptions.currentPlatform,
        );
      }

      final messaging = FirebaseMessaging.instance;

      final settings = await messaging.requestPermission(
        alert:         true,
        badge:         true,
        sound:         true,
        criticalAlert: true,
      );
      if (kDebugMode) {
        debugPrint('[FCM] permission: ${settings.authorizationStatus}');
      }

      _token = await messaging.getToken();
      if (_token != null) await _registerTokenWithBackend(_token!);

      messaging.onTokenRefresh.listen((newToken) async {
        _token = newToken;
        await _registerTokenWithBackend(newToken);
      });

      FirebaseMessaging.onMessage.listen(_handleMessage);
      FirebaseMessaging.onMessageOpenedApp.listen(_handleMessageTap);

      final initial = await messaging.getInitialMessage();
      if (initial != null) _handleMessageTap(initial);

      FirebaseMessaging.onBackgroundMessage(_fcmBackgroundHandler);

      if (kDebugMode) debugPrint('[FCM] ✅ Live mode active. Token: $_token');
    } catch (e) {
      if (kDebugMode) debugPrint('[FCM] ⚠️  init failed: $e');
    }
  }

  Future<void> _registerTokenWithBackend(String token) async {
    try {
      final prefs = await SharedPreferences.getInstance();
      if (prefs.getString(_tokenKey) == token) return;

      final res = await http
          .post(
            Uri.parse('${AppConstants.baseUrl}/api/register-device'),
            headers: {'Content-Type': 'application/json'},
            body: jsonEncode({
              'token':    token,
              'platform': defaultTargetPlatform.name.toLowerCase(),
              'app':      'equinox_android_v2',
            }),
          )
          .timeout(const Duration(seconds: 10));

      if (res.statusCode == 200 || res.statusCode == 201) {
        await prefs.setString(_tokenKey, token);
        if (kDebugMode) debugPrint('[FCM] ✅ device token registered');
      }
    } catch (e) {
      if (kDebugMode) debugPrint('[FCM] registration error: $e');
    }
  }

  void _handleMessage(RemoteMessage msg) {
    try {
      final data = msg.data.map((k, v) => MapEntry(k, v.toString()));
      if (msg.notification?.title != null) {
        data['city']    = data['city']    ?? msg.notification!.title!;
        data['message'] = data['message'] ?? msg.notification!.body ?? '';
      }
      final alert = FcmFloodAlert.fromMap(data);
      _alertController.add(alert);
      _showLocalNotification(alert);
    } catch (e) {
      if (kDebugMode) debugPrint('[FCM] handleMessage error: $e');
    }
  }

  void _handleMessageTap(RemoteMessage msg) {
    try {
      final alert = FcmFloodAlert.fromMap(
          msg.data.map((k, v) => MapEntry(k, v.toString())));
      _alertController.add(alert);
    } catch (e) {
      if (kDebugMode) debugPrint('[FCM] handleTap error: $e');
    }
  }

  Future<void> _showLocalNotification(FcmFloodAlert alert) async {
    final plugin     = FlutterLocalNotificationsPlugin();
    final isCritical = alert.severity == 'CRITICAL';
    final body = alert.message.isNotEmpty
        ? alert.message
        : '${alert.river} is at ${alert.currentLevel.toStringAsFixed(1)}m '
          '(danger: ${alert.dangerLevel.toStringAsFixed(1)}m)';

    await plugin.show(
      _stableId(alert.city),
      '${isCritical ? "\uD83D\uDEA8" : "\u26A0\uFE0F"} ${alert.city} — ${alert.severity}',
      body,
      NotificationDetails(
        android: AndroidNotificationDetails(
          isCritical ? AppConstants.criticalAlertChannelId : AppConstants.warningAlertChannelId,
          isCritical ? AppConstants.criticalAlertChannelName : AppConstants.warningAlertChannelName,
          importance: isCritical ? Importance.max  : Importance.high,
          priority:   isCritical ? Priority.max    : Priority.high,
          ongoing:    isCritical,
          autoCancel: !isCritical,
        ),
        iOS: const DarwinNotificationDetails(
          presentAlert: true,
          presentSound: true,
          interruptionLevel: InterruptionLevel.timeSensitive,
        ),
      ),
      payload: 'city=${alert.city}&severity=${alert.severity}',
    );
  }

  Future<void> unregister() async {
    try { await FirebaseMessaging.instance.deleteToken(); } catch (_) {}
    final prefs = await SharedPreferences.getInstance();
    await prefs.remove(_tokenKey);
    _token = null;
  }

  void dispose() => _alertController.close();

  int _stableId(String city) =>
      city.codeUnits.fold(0, (int a, int b) => (a * 31 + b) & 0x7FFFFFFF);
}
