// Equinox Flood — Firebase Cloud Messaging (FCM) Service
// ─────────────────────────────────────────────────────────────────────────────
// P1: Real push delivery for critical flood alerts.
//
// ARCHITECTURE:
//   Backend (OpsFlood FastAPI) calls:
//     POST https://fcm.googleapis.com/v1/projects/{project}/messages:send
//   With the Server Key stored as env var FIREBASE_SERVER_KEY on Render.
//
//   App-side (this file):
//     1. Initialise firebase_core + firebase_messaging
//     2. Get FCM token → POST to /api/register-device on OpsFlood backend
//     3. Handle foreground / background / terminated messages
//     4. Map FCM payload to local notification via flutter_local_notifications
//
// SETUP CHECKLIST (one-time, local machine):
//   1. Firebase Console → create project → add Android app
//      (package: com.opsflood.android) → download google-services.json
//      → place in android/app/
//   2. Run: flutterfire configure  (generates lib/firebase_options.dart)
//   3. Add to android/build.gradle:  classpath 'com.google.gms:google-services:4.4.0'
//   4. Add to android/app/build.gradle: apply plugin: 'com.google.gms.google-services'
//   5. On Render (OpsFlood): set FIREBASE_SERVER_KEY env var
// ─────────────────────────────────────────────────────────────────────────────

import 'dart:async';
import 'dart:convert';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';

import '../constants.dart';
// ignore: uri_does_not_exist — generated by flutterfire configure
import '../firebase_options.dart';

// ─── FCM Payload ──────────────────────────────────────────────────────────────
class FcmFloodAlert {
  final String city;
  final String state;
  final String severity;       // CRITICAL | HIGH | MODERATE
  final String river;
  final double currentLevel;
  final double dangerLevel;
  final String message;
  final DateTime receivedAt;

  const FcmFloodAlert({
    required this.city,
    required this.state,
    required this.severity,
    required this.river,
    required this.currentLevel,
    required this.dangerLevel,
    required this.message,
    required this.receivedAt,
  });

  factory FcmFloodAlert.fromMap(Map<String, dynamic> data) {
    double sf(dynamic v) =>
        v == null ? 0.0 : (double.tryParse(v.toString()) ?? 0.0);
    return FcmFloodAlert(
      city:         (data['city']          ?? data['location'] ?? 'Unknown').toString(),
      state:        (data['state']         ?? '').toString(),
      severity:     (data['severity']      ?? 'HIGH').toString().toUpperCase(),
      river:        (data['river']         ?? data['river_name'] ?? '').toString(),
      currentLevel: sf(data['current_level'] ?? data['river_level']),
      dangerLevel:  sf(data['danger_level']),
      message:      (data['message']       ?? data['body'] ?? '').toString(),
      receivedAt:   DateTime.now(),
    );
  }
}

// ── Background FCM handler — top-level, runs in separate Dart isolate ─────────
// Must be top-level (not a class method) per firebase_messaging requirement.
@pragma('vm:entry-point')
Future<void> _fcmBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  if (kDebugMode) debugPrint('[FCM-BG] ${message.data}');
  // Background data-only messages are NOT auto-shown on Android.
  // Show manually if needed — for now we rely on notification payload
  // being set by the backend so the OS shows it automatically.
}

// ─── FCM Service ──────────────────────────────────────────────────────────────
class FcmService {
  FcmService._();
  static final FcmService instance = FcmService._();

  static const _tokenKey = 'equinox_fcm_token';

  final _alertController = StreamController<FcmFloodAlert>.broadcast();
  Stream<FcmFloodAlert> get alertStream => _alertController.stream;

  String? _token;
  String? get token => _token;

  bool _initialized = false;

  // ── INIT ─────────────────────────────────────────────────────────────────
  // Call once from SplashScreen after backend health check.
  Future<void> init() async {
    if (_initialized) return;
    _initialized = true;

    try {
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );

      final messaging = FirebaseMessaging.instance;

      // Request permission (iOS + Android 13+ require explicit grant).
      final settings = await messaging.requestPermission(
        alert:         true,
        badge:         true,
        sound:         true,
        criticalAlert: true,   // breaks through Do-Not-Disturb on iOS
      );
      if (kDebugMode) {
        debugPrint('[FCM] permission: ${settings.authorizationStatus}');
      }

      // Get device token and register with OpsFlood backend.
      _token = await messaging.getToken();
      if (_token != null) {
        await _registerTokenWithBackend(_token!);
      }

      // Token rotates ~every 60 days — keep backend in sync.
      messaging.onTokenRefresh.listen((newToken) async {
        _token = newToken;
        await _registerTokenWithBackend(newToken);
      });

      // ── FOREGROUND messages ─────────────────────────────────────────────
      // FCM does NOT auto-show a notification when the app is open.
      // We show one manually via flutter_local_notifications.
      FirebaseMessaging.onMessage.listen(_handleMessage);

      // ── BACKGROUND tap (app was backgrounded, user tapped notification) ─
      FirebaseMessaging.onMessageOpenedApp.listen(_handleMessageTap);

      // ── TERMINATED tap (app was closed, user tapped notification) ───────
      final initial = await messaging.getInitialMessage();
      if (initial != null) _handleMessageTap(initial);

      // ── BACKGROUND handler (separate isolate) ────────────────────────────
      FirebaseMessaging.onBackgroundMessage(_fcmBackgroundHandler);

      if (kDebugMode) debugPrint('[FCM] ✅ Live mode active. Token: $_token');
    } catch (e) {
      // Never crash the app if Firebase setup is incomplete.
      if (kDebugMode) debugPrint('[FCM] ⚠️  init failed (check flutterfire configure): $e');
    }
  }

  // ── Register device token with OpsFlood backend ───────────────────────────
  Future<void> _registerTokenWithBackend(String token) async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final old   = prefs.getString(_tokenKey);
      if (old == token) return;   // already registered — skip

      final res = await http
          .post(
            Uri.parse('${AppConstants.baseUrl}/api/register-device'),
            headers: {'Content-Type': 'application/json'},
            body: jsonEncode({
              'token':    token,
              'platform': defaultTargetPlatform.name.toLowerCase(),
              'app':      'equinox_android_v2',
            }),
          )
          .timeout(const Duration(seconds: 10));

      if (res.statusCode == 200 || res.statusCode == 201) {
        await prefs.setString(_tokenKey, token);
        if (kDebugMode) debugPrint('[FCM] ✅ device token registered');
      } else {
        if (kDebugMode) debugPrint('[FCM] ⚠️  registration failed: ${res.statusCode}');
      }
    } catch (e) {
      if (kDebugMode) debugPrint('[FCM] registration error: $e');
    }
  }

  // ── Handle incoming FCM message (foreground) ──────────────────────────────
  void _handleMessage(RemoteMessage msg) {
    try {
      final data = msg.data.map((k, v) => MapEntry(k, v.toString()));
      // Merge notification title/body into data map for uniform parsing.
      if (msg.notification?.title != null) {
        data['city']    = data['city']    ?? msg.notification!.title!;
        data['message'] = data['message'] ?? msg.notification!.body ?? '';
      }
      final alert = FcmFloodAlert.fromMap(data);
      _alertController.add(alert);
      _showLocalNotification(alert);
      if (kDebugMode) debugPrint('[FCM] foreground alert: ${alert.city} ${alert.severity}');
    } catch (e) {
      if (kDebugMode) debugPrint('[FCM] handleMessage error: $e');
    }
  }

  // ── Handle notification tap ───────────────────────────────────────────────
  void _handleMessageTap(RemoteMessage msg) {
    try {
      final data = msg.data.map((k, v) => MapEntry(k, v.toString()));
      final alert = FcmFloodAlert.fromMap(data);
      _alertController.add(alert);   // screens receive this and can navigate
      if (kDebugMode) debugPrint('[FCM] tapped alert: ${alert.city}');
    } catch (e) {
      if (kDebugMode) debugPrint('[FCM] handleTap error: $e');
    }
  }

  // ── Show local notification for foreground FCM message ───────────────────
  Future<void> _showLocalNotification(FcmFloodAlert alert) async {
    final plugin      = FlutterLocalNotificationsPlugin();
    final isCritical  = alert.severity == 'CRITICAL';
    await plugin.show(
      id:    _stableId(alert.city),
      title: '${isCritical ? "🚨" : "⚠️"} ${alert.city} — ${alert.severity}',
      body:  alert.message.isNotEmpty
          ? alert.message
          : '${alert.river} is at ${alert.currentLevel.toStringAsFixed(1)}m '
            '(danger: ${alert.dangerLevel.toStringAsFixed(1)}m)',
      notificationDetails: NotificationDetails(
        android: AndroidNotificationDetails(
          isCritical
              ? AppConstants.criticalAlertChannelId
              : AppConstants.warningAlertChannelId,
          isCritical
              ? AppConstants.criticalAlertChannelName
              : AppConstants.warningAlertChannelName,
          importance: isCritical ? Importance.max  : Importance.high,
          priority:   isCritical ? Priority.max    : Priority.high,
          ongoing:    isCritical,
          autoCancel: !isCritical,
        ),
        iOS: const DarwinNotificationDetails(
          presentAlert: true,
          presentSound: true,
          interruptionLevel: InterruptionLevel.timeSensitive,
        ),
      ),
      payload: 'city=${alert.city}&severity=${alert.severity}',
    );
  }

  // ── Unregister on logout ──────────────────────────────────────────────────
  Future<void> unregister() async {
    try {
      await FirebaseMessaging.instance.deleteToken();
    } catch (_) {}
    final prefs = await SharedPreferences.getInstance();
    await prefs.remove(_tokenKey);
    _token = null;
    if (kDebugMode) debugPrint('[FCM] token unregistered');
  }

  void dispose() => _alertController.close();

  // Stable notification ID — polynomial hash of city name.
  int _stableId(String city) =>
      city.codeUnits.fold(0, (int a, int b) => (a * 31 + b) & 0x7FFFFFFF);
}
