// lib/constants/india_geodata.dart
//
// OpsFlood Bihar — Geodata constants (v2.0 Bihar-only)
//
// REPLACES the pan-India 36-state + 90-city list.
// monitoredCities now mirrors kIndiaCities (31 WRD Bihar gauges).
// The 'states' list is kept as a single-item list so that any dropdown
// or filter in the UI automatically shows only Bihar.

class IndiaGeodata {
  // Single-state list — the app is Bihar-only.
  static const List<String> states = ['Bihar'];

  // 31 WRD Bihar gauge stations (mirrors lib/data/india_cities.dart).
  static const List<Map<String, dynamic>> monitoredCities = [
    // ── GANGA ──────────────────────────────────────────────────────────────
    { 'city': 'Gandhighat',     'state': 'Bihar', 'river': 'Ganga',
      'lat': 25.6129, 'lon': 85.1376,
      'danger_level': 48.60, 'warning_level': 47.50,
      'risk': 'HIGH',  'flood_freq': 0.82, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Dighaghat',      'state': 'Bihar', 'river': 'Ganga',
      'lat': 25.5941, 'lon': 85.0700,
      'danger_level': 50.45, 'warning_level': 49.30,
      'risk': 'HIGH',  'flood_freq': 0.80, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Hathidah',       'state': 'Bihar', 'river': 'Ganga',
      'lat': 25.4167, 'lon': 85.7500,
      'danger_level': 41.76, 'warning_level': 40.50,
      'risk': 'HIGH',  'flood_freq': 0.78, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Munger',         'state': 'Bihar', 'river': 'Ganga',
      'lat': 25.3743, 'lon': 86.4730,
      'danger_level': 39.33, 'warning_level': 38.20,
      'risk': 'HIGH',  'flood_freq': 0.76, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Kahalgaon',      'state': 'Bihar', 'river': 'Ganga',
      'lat': 25.2167, 'lon': 87.2667,
      'danger_level': 31.09, 'warning_level': 30.00,
      'risk': 'HIGH',  'flood_freq': 0.74, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Bhagalpur',      'state': 'Bihar', 'river': 'Ganga',
      'lat': 25.2425, 'lon': 86.9842,
      'danger_level': 33.68, 'warning_level': 32.50,
      'risk': 'HIGH',  'flood_freq': 0.78, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Buxar',          'state': 'Bihar', 'river': 'Ganga',
      'lat': 25.5667, 'lon': 83.9667,
      'danger_level': 60.30, 'warning_level': 59.20,
      'risk': 'MODERATE', 'flood_freq': 0.65, 'river_type': 'perennial', 'zone': 'himalayan' },
    // ── KOSI ───────────────────────────────────────────────────────────────
    { 'city': 'Birpur',         'state': 'Bihar', 'river': 'Kosi',
      'lat': 26.5167, 'lon': 86.9000,
      'danger_level': 74.70, 'warning_level': 73.70,
      'risk': 'CRITICAL', 'flood_freq': 0.92, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Baltara',        'state': 'Bihar', 'river': 'Kosi',
      'lat': 25.5000, 'lon': 86.5833,
      'danger_level': 33.85, 'warning_level': 32.85,
      'risk': 'HIGH',  'flood_freq': 0.85, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Basua',          'state': 'Bihar', 'river': 'Kosi',
      'lat': 26.1234, 'lon': 86.6020,
      'danger_level': 47.75, 'warning_level': 46.50,
      'risk': 'HIGH',  'flood_freq': 0.88, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Kursela',        'state': 'Bihar', 'river': 'Kosi',
      'lat': 25.4800, 'lon': 87.2600,
      'danger_level': 30.00, 'warning_level': 28.80,
      'risk': 'HIGH',  'flood_freq': 0.82, 'river_type': 'perennial', 'zone': 'himalayan' },
    // ── GANDAK ─────────────────────────────────────────────────────────────
    { 'city': 'Chatia',         'state': 'Bihar', 'river': 'Gandak',
      'lat': 26.8500, 'lon': 84.9000,
      'danger_level': 69.15, 'warning_level': 68.10,
      'risk': 'HIGH',  'flood_freq': 0.78, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Dumariaghat',    'state': 'Bihar', 'river': 'Gandak',
      'lat': 26.4833, 'lon': 84.4667,
      'danger_level': 62.22, 'warning_level': 61.10,
      'risk': 'HIGH',  'flood_freq': 0.80, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Rewaghat',       'state': 'Bihar', 'river': 'Gandak',
      'lat': 26.1000, 'lon': 85.3000,
      'danger_level': 54.41, 'warning_level': 53.40,
      'risk': 'HIGH',  'flood_freq': 0.80, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Hajipur',        'state': 'Bihar', 'river': 'Gandak',
      'lat': 25.6933, 'lon': 85.2094,
      'danger_level': 50.32, 'warning_level': 49.40,
      'risk': 'HIGH',  'flood_freq': 0.76, 'river_type': 'perennial', 'zone': 'himalayan' },
    // ── BAGMATI ────────────────────────────────────────────────────────────
    { 'city': 'Dheng Bridge',   'state': 'Bihar', 'river': 'Bagmati',
      'lat': 26.5800, 'lon': 85.4900,
      'danger_level': 71.00, 'warning_level': 70.00,
      'risk': 'HIGH',  'flood_freq': 0.82, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Benibad',        'state': 'Bihar', 'river': 'Bagmati',
      'lat': 26.0500, 'lon': 85.6500,
      'danger_level': 48.68, 'warning_level': 47.68,
      'risk': 'HIGH',  'flood_freq': 0.80, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Hayaghat',       'state': 'Bihar', 'river': 'Bagmati',
      'lat': 26.0200, 'lon': 85.9500,
      'danger_level': 45.72, 'warning_level': 44.50,
      'risk': 'HIGH',  'flood_freq': 0.78, 'river_type': 'perennial', 'zone': 'himalayan' },
    // ── BURHI GANDAK ───────────────────────────────────────────────────────
    { 'city': 'Sikandarpur',    'state': 'Bihar', 'river': 'Burhi Gandak',
      'lat': 26.1209, 'lon': 85.3647,
      'danger_level': 52.53, 'warning_level': 51.40,
      'risk': 'HIGH',  'flood_freq': 0.75, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Samastipur',     'state': 'Bihar', 'river': 'Burhi Gandak',
      'lat': 25.8620, 'lon': 85.7812,
      'danger_level': 46.00, 'warning_level': 44.80,
      'risk': 'HIGH',  'flood_freq': 0.73, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Rosera',         'state': 'Bihar', 'river': 'Burhi Gandak',
      'lat': 25.8600, 'lon': 85.9800,
      'danger_level': 42.63, 'warning_level': 41.50,
      'risk': 'MODERATE', 'flood_freq': 0.68, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Khagaria',       'state': 'Bihar', 'river': 'Burhi Gandak',
      'lat': 25.5000, 'lon': 86.4700,
      'danger_level': 36.58, 'warning_level': 35.40,
      'risk': 'HIGH',  'flood_freq': 0.72, 'river_type': 'perennial', 'zone': 'himalayan' },
    // ── GHAGHRA ────────────────────────────────────────────────────────────
    { 'city': 'Darauli',        'state': 'Bihar', 'river': 'Ghaghra',
      'lat': 25.9500, 'lon': 84.1500,
      'danger_level': 60.82, 'warning_level': 59.80,
      'risk': 'HIGH',  'flood_freq': 0.70, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Gangpur Siswan', 'state': 'Bihar', 'river': 'Ghaghra',
      'lat': 26.0500, 'lon': 84.4000,
      'danger_level': 57.04, 'warning_level': 56.00,
      'risk': 'HIGH',  'flood_freq': 0.68, 'river_type': 'perennial', 'zone': 'himalayan' },
    // ── MAHANANDA ──────────────────────────────────────────────────────────
    { 'city': 'Dhengraghat',    'state': 'Bihar', 'river': 'Mahananda',
      'lat': 25.7800, 'lon': 87.4800,
      'danger_level': 35.65, 'warning_level': 34.65,
      'risk': 'HIGH',  'flood_freq': 0.72, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Taibpur',        'state': 'Bihar', 'river': 'Mahananda',
      'lat': 26.5800, 'lon': 87.9500,
      'danger_level': 66.00, 'warning_level': 64.80,
      'risk': 'HIGH',  'flood_freq': 0.70, 'river_type': 'perennial', 'zone': 'himalayan' },
    // ── KAMLA / KAMALABALAN ────────────────────────────────────────────────
    { 'city': 'Jainagar',       'state': 'Bihar', 'river': 'Kamla',
      'lat': 26.6000, 'lon': 86.2700,
      'danger_level': 67.75, 'warning_level': 66.00,
      'risk': 'HIGH',  'flood_freq': 0.80, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Jhanjharpur',    'state': 'Bihar', 'river': 'Kamalabalan',
      'lat': 26.2700, 'lon': 86.2800,
      'danger_level': 50.00, 'warning_level': 48.80,
      'risk': 'HIGH',  'flood_freq': 0.78, 'river_type': 'perennial', 'zone': 'himalayan' },
    // ── ADHWARA ────────────────────────────────────────────────────────────
    { 'city': 'Sonbarsa',       'state': 'Bihar', 'river': 'Adhwara',
      'lat': 26.6500, 'lon': 85.5500,
      'danger_level': 81.85, 'warning_level': 80.70,
      'risk': 'HIGH',  'flood_freq': 0.82, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Kamtaul',        'state': 'Bihar', 'river': 'Adhwara',
      'lat': 26.2200, 'lon': 85.8500,
      'danger_level': 50.00, 'warning_level': 49.00,
      'risk': 'HIGH',  'flood_freq': 0.80, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Ekmighat',       'state': 'Bihar', 'river': 'Adhwara',
      'lat': 26.1500, 'lon': 86.0000,
      'danger_level': 46.94, 'warning_level': 45.80,
      'risk': 'HIGH',  'flood_freq': 0.78, 'river_type': 'perennial', 'zone': 'himalayan' },
    // ── PUNPUN ─────────────────────────────────────────────────────────────
    { 'city': 'Sripalpur',      'state': 'Bihar', 'river': 'Punpun',
      'lat': 25.4833, 'lon': 85.1333,
      'danger_level': 50.60, 'warning_level': 49.50,
      'risk': 'MODERATE', 'flood_freq': 0.55, 'river_type': 'perennial', 'zone': 'himalayan' },
  ];
}
