// lib/constants/india_geodata.dart
//
// EQUINOX-BH — Geodata constants (v5.1 — add WRD-only stations)
//
// v5.1: Added Manpur and other WRD Bihar backend stations that were
//       missing from monitoredCities, causing the city detail screen
//       to spin forever (cityDataProvider returned null indefinitely).
//       Rule: every station the WRD backend can return must have an
//       entry here so LiveFetchEngine._cache[key] is populated.
//
// v5.0: Removed all non-Bihar cities and states.
//       monitoredCities now contains only Bihar flood-monitoring stations.
//       states list trimmed to ['Bihar'] — app scope is Bihar-specific.

class IndiaGeodata {
  static const List<String> states = ['Bihar'];

  static const List<Map<String, dynamic>> monitoredCities = [
    // ── Ganga ──────────────────────────────────────────────────────────────
    { 'city': 'Gandhighat',     'district': 'Patna',          'state': 'Bihar', 'river': 'Ganga',
      'lat': 25.6129, 'lon': 85.1376,
      'danger_level': 48.60, 'warning_level': 47.50,
      'risk': 'HIGH',     'flood_freq': 0.82, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Dighaghat',      'district': 'Patna',          'state': 'Bihar', 'river': 'Ganga',
      'lat': 25.5941, 'lon': 85.0700,
      'danger_level': 50.45, 'warning_level': 49.30,
      'risk': 'HIGH',     'flood_freq': 0.80, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Hathidah',       'district': 'Lakhisarai',     'state': 'Bihar', 'river': 'Ganga',
      'lat': 25.4167, 'lon': 85.7500,
      'danger_level': 41.76, 'warning_level': 40.50,
      'risk': 'HIGH',     'flood_freq': 0.78, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Munger',         'district': 'Munger',         'state': 'Bihar', 'river': 'Ganga',
      'lat': 25.3743, 'lon': 86.4730,
      'danger_level': 39.33, 'warning_level': 38.20,
      'risk': 'HIGH',     'flood_freq': 0.76, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Kahalgaon',      'district': 'Bhagalpur',      'state': 'Bihar', 'river': 'Ganga',
      'lat': 25.2167, 'lon': 87.2667,
      'danger_level': 31.09, 'warning_level': 30.00,
      'risk': 'HIGH',     'flood_freq': 0.74, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Bhagalpur',      'district': 'Bhagalpur',      'state': 'Bihar', 'river': 'Ganga',
      'lat': 25.2425, 'lon': 86.9842,
      'danger_level': 33.68, 'warning_level': 32.50,
      'risk': 'HIGH',     'flood_freq': 0.78, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Buxar',          'district': 'Buxar',          'state': 'Bihar', 'river': 'Ganga',
      'lat': 25.5667, 'lon': 83.9667,
      'danger_level': 60.30, 'warning_level': 59.20,
      'risk': 'MODERATE', 'flood_freq': 0.65, 'river_type': 'perennial', 'zone': 'himalayan' },
    // ── Ganga (WRD-only stations added v5.1) ───────────────────────────────
    { 'city': 'Manpur',         'district': 'Gopalganj',      'state': 'Bihar', 'river': 'Gandak',
      'lat': 26.4700, 'lon': 84.4300,
      'danger_level': 62.00, 'warning_level': 60.80,
      'risk': 'HIGH',     'flood_freq': 0.75, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Gopalpur',       'district': 'Samastipur',     'state': 'Bihar', 'river': 'Burhi Gandak',
      'lat': 25.8800, 'lon': 85.8200,
      'danger_level': 44.00, 'warning_level': 43.00,
      'risk': 'HIGH',     'flood_freq': 0.70, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Bhairoghat',     'district': 'Patna',          'state': 'Bihar', 'river': 'Ganga',
      'lat': 25.6200, 'lon': 85.2000,
      'danger_level': 49.00, 'warning_level': 47.80,
      'risk': 'HIGH',     'flood_freq': 0.78, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Digha',          'district': 'Patna',          'state': 'Bihar', 'river': 'Ganga',
      'lat': 25.6100, 'lon': 85.0500,
      'danger_level': 50.60, 'warning_level': 49.50,
      'risk': 'HIGH',     'flood_freq': 0.80, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Patna Sahib',    'district': 'Patna',          'state': 'Bihar', 'river': 'Ganga',
      'lat': 25.6200, 'lon': 85.2100,
      'danger_level': 48.80, 'warning_level': 47.60,
      'risk': 'HIGH',     'flood_freq': 0.80, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Mokama',         'district': 'Patna',          'state': 'Bihar', 'river': 'Ganga',
      'lat': 25.4000, 'lon': 85.9200,
      'danger_level': 42.00, 'warning_level': 40.80,
      'risk': 'HIGH',     'flood_freq': 0.75, 'river_type': 'perennial', 'zone': 'himalayan' },
    // ── Kosi ───────────────────────────────────────────────────────────────
    { 'city': 'Birpur',         'district': 'Supaul',         'state': 'Bihar', 'river': 'Kosi',
      'lat': 26.5167, 'lon': 86.9000,
      'danger_level': 74.70, 'warning_level': 73.70,
      'risk': 'CRITICAL', 'flood_freq': 0.92, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Baltara',        'district': 'Saharsa',        'state': 'Bihar', 'river': 'Kosi',
      'lat': 25.5000, 'lon': 86.5833,
      'danger_level': 33.85, 'warning_level': 32.85,
      'risk': 'HIGH',     'flood_freq': 0.85, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Basua',          'district': 'Madhubani',      'state': 'Bihar', 'river': 'Kosi',
      'lat': 26.1234, 'lon': 86.6020,
      'danger_level': 47.75, 'warning_level': 46.50,
      'risk': 'HIGH',     'flood_freq': 0.88, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Kursela',        'district': 'Katihar',        'state': 'Bihar', 'river': 'Kosi',
      'lat': 25.4800, 'lon': 87.2600,
      'danger_level': 30.00, 'warning_level': 28.80,
      'risk': 'HIGH',     'flood_freq': 0.82, 'river_type': 'perennial', 'zone': 'himalayan' },
    // ── Gandak ─────────────────────────────────────────────────────────────
    { 'city': 'Chatia',         'district': 'East Champaran', 'state': 'Bihar', 'river': 'Gandak',
      'lat': 26.8500, 'lon': 84.9000,
      'danger_level': 69.15, 'warning_level': 68.10,
      'risk': 'HIGH',     'flood_freq': 0.78, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Dumariaghat',    'district': 'Gopalganj',      'state': 'Bihar', 'river': 'Gandak',
      'lat': 26.4833, 'lon': 84.4667,
      'danger_level': 62.22, 'warning_level': 61.10,
      'risk': 'HIGH',     'flood_freq': 0.80, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Rewaghat',       'district': 'Muzaffarpur',    'state': 'Bihar', 'river': 'Gandak',
      'lat': 26.1000, 'lon': 85.3000,
      'danger_level': 54.41, 'warning_level': 53.40,
      'risk': 'HIGH',     'flood_freq': 0.80, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Hajipur',        'district': 'Vaishali',       'state': 'Bihar', 'river': 'Gandak',
      'lat': 25.6933, 'lon': 85.2094,
      'danger_level': 50.32, 'warning_level': 49.40,
      'risk': 'HIGH',     'flood_freq': 0.76, 'river_type': 'perennial', 'zone': 'himalayan' },
    // ── Bagmati ────────────────────────────────────────────────────────────
    { 'city': 'Dheng Bridge',   'district': 'Sitamarhi',      'state': 'Bihar', 'river': 'Bagmati',
      'lat': 26.5800, 'lon': 85.4900,
      'danger_level': 71.00, 'warning_level': 70.00,
      'risk': 'HIGH',     'flood_freq': 0.82, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Benibad',        'district': 'Darbhanga',      'state': 'Bihar', 'river': 'Bagmati',
      'lat': 26.0500, 'lon': 85.6500,
      'danger_level': 48.68, 'warning_level': 47.68,
      'risk': 'HIGH',     'flood_freq': 0.80, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Hayaghat',       'district': 'Darbhanga',      'state': 'Bihar', 'river': 'Bagmati',
      'lat': 26.0200, 'lon': 85.9500,
      'danger_level': 45.72, 'warning_level': 44.50,
      'risk': 'HIGH',     'flood_freq': 0.78, 'river_type': 'perennial', 'zone': 'himalayan' },
    // ── Burhi Gandak ───────────────────────────────────────────────────────
    { 'city': 'Sikandarpur',    'district': 'East Champaran', 'state': 'Bihar', 'river': 'Burhi Gandak',
      'lat': 26.1209, 'lon': 85.3647,
      'danger_level': 52.53, 'warning_level': 51.40,
      'risk': 'HIGH',     'flood_freq': 0.75, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Samastipur',     'district': 'Samastipur',     'state': 'Bihar', 'river': 'Burhi Gandak',
      'lat': 25.8620, 'lon': 85.7812,
      'danger_level': 46.00, 'warning_level': 44.80,
      'risk': 'HIGH',     'flood_freq': 0.73, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Rosera',         'district': 'Samastipur',     'state': 'Bihar', 'river': 'Burhi Gandak',
      'lat': 25.8600, 'lon': 85.9800,
      'danger_level': 42.63, 'warning_level': 41.50,
      'risk': 'MODERATE', 'flood_freq': 0.68, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Khagaria',       'district': 'Khagaria',       'state': 'Bihar', 'river': 'Burhi Gandak',
      'lat': 25.5000, 'lon': 86.4700,
      'danger_level': 36.58, 'warning_level': 35.40,
      'risk': 'HIGH',     'flood_freq': 0.72, 'river_type': 'perennial', 'zone': 'himalayan' },
    // ── Ghaghra ────────────────────────────────────────────────────────────
    { 'city': 'Darauli',        'district': 'Siwan',          'state': 'Bihar', 'river': 'Ghaghra',
      'lat': 25.9500, 'lon': 84.1500,
      'danger_level': 60.82, 'warning_level': 59.80,
      'risk': 'HIGH',     'flood_freq': 0.70, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Gangpur Siswan', 'district': 'Siwan',          'state': 'Bihar', 'river': 'Ghaghra',
      'lat': 26.0500, 'lon': 84.4000,
      'danger_level': 57.04, 'warning_level': 56.00,
      'risk': 'HIGH',     'flood_freq': 0.68, 'river_type': 'perennial', 'zone': 'himalayan' },
    // ── Mahananda ──────────────────────────────────────────────────────────
    { 'city': 'Dhengraghat',    'district': 'Kishanganj',     'state': 'Bihar', 'river': 'Mahananda',
      'lat': 25.7800, 'lon': 87.4800,
      'danger_level': 35.65, 'warning_level': 34.65,
      'risk': 'HIGH',     'flood_freq': 0.72, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Taibpur',        'district': 'Araria',         'state': 'Bihar', 'river': 'Mahananda',
      'lat': 26.5800, 'lon': 87.9500,
      'danger_level': 66.00, 'warning_level': 64.80,
      'risk': 'HIGH',     'flood_freq': 0.70, 'river_type': 'perennial', 'zone': 'himalayan' },
    // ── Kamla / Kamalabalan ────────────────────────────────────────────────
    { 'city': 'Jainagar',       'district': 'Madhubani',      'state': 'Bihar', 'river': 'Kamla',
      'lat': 26.6000, 'lon': 86.2700,
      'danger_level': 67.75, 'warning_level': 66.00,
      'risk': 'HIGH',     'flood_freq': 0.80, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Jhanjharpur',    'district': 'Madhubani',      'state': 'Bihar', 'river': 'Kamalabalan',
      'lat': 26.2700, 'lon': 86.2800,
      'danger_level': 50.00, 'warning_level': 48.80,
      'risk': 'HIGH',     'flood_freq': 0.78, 'river_type': 'perennial', 'zone': 'himalayan' },
    // ── Adhwara ────────────────────────────────────────────────────────────
    { 'city': 'Sonbarsa',       'district': 'Sitamarhi',      'state': 'Bihar', 'river': 'Adhwara',
      'lat': 26.6500, 'lon': 85.5500,
      'danger_level': 81.85, 'warning_level': 80.70,
      'risk': 'HIGH',     'flood_freq': 0.82, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Kamtaul',        'district': 'Darbhanga',      'state': 'Bihar', 'river': 'Adhwara',
      'lat': 26.2200, 'lon': 85.8500,
      'danger_level': 50.00, 'warning_level': 49.00,
      'risk': 'HIGH',     'flood_freq': 0.80, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Ekmighat',       'district': 'Madhubani',      'state': 'Bihar', 'river': 'Adhwara',
      'lat': 26.1500, 'lon': 86.0000,
      'danger_level': 46.94, 'warning_level': 45.80,
      'risk': 'HIGH',     'flood_freq': 0.78, 'river_type': 'perennial', 'zone': 'himalayan' },
    // ── Punpun ─────────────────────────────────────────────────────────────
    { 'city': 'Sripalpur',      'district': 'Patna',          'state': 'Bihar', 'river': 'Punpun',
      'lat': 25.4833, 'lon': 85.1333,
      'danger_level': 50.60, 'warning_level': 49.50,
      'risk': 'MODERATE', 'flood_freq': 0.55, 'river_type': 'perennial', 'zone': 'himalayan' },
  ];
}
