// lib/constants/india_geodata.dart
//
// OpsFlood — Geodata constants (v4.0 — district/zila added)

class IndiaGeodata {
  static const List<String> states = [
    'Andhra Pradesh','Arunachal Pradesh','Assam','Bihar','Chhattisgarh',
    'Goa','Gujarat','Haryana','Himachal Pradesh','Jharkhand','Karnataka',
    'Kerala','Madhya Pradesh','Maharashtra','Manipur','Meghalaya','Mizoram',
    'Nagaland','Odisha','Punjab','Rajasthan','Sikkim','Tamil Nadu',
    'Telangana','Tripura','Uttar Pradesh','Uttarakhand','West Bengal',
    'Andaman and Nicobar Islands','Chandigarh',
    'Dadra and Nagar Haveli and Daman and Diu','Delhi',
    'Jammu and Kashmir','Ladakh','Lakshadweep','Puducherry',
  ];

  static const List<Map<String, dynamic>> monitoredCities = [
    // ── BIHAR — Ganga ──────────────────────────────────────────────────────
    { 'city': 'Gandhighat',     'district': 'Patna',          'state': 'Bihar', 'river': 'Ganga',
      'lat': 25.6129, 'lon': 85.1376,
      'danger_level': 48.60, 'warning_level': 47.50,
      'risk': 'HIGH',  'flood_freq': 0.82, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Dighaghat',      'district': 'Patna',          'state': 'Bihar', 'river': 'Ganga',
      'lat': 25.5941, 'lon': 85.0700,
      'danger_level': 50.45, 'warning_level': 49.30,
      'risk': 'HIGH',  'flood_freq': 0.80, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Hathidah',       'district': 'Lakhisarai',     'state': 'Bihar', 'river': 'Ganga',
      'lat': 25.4167, 'lon': 85.7500,
      'danger_level': 41.76, 'warning_level': 40.50,
      'risk': 'HIGH',  'flood_freq': 0.78, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Munger',         'district': 'Munger',         'state': 'Bihar', 'river': 'Ganga',
      'lat': 25.3743, 'lon': 86.4730,
      'danger_level': 39.33, 'warning_level': 38.20,
      'risk': 'HIGH',  'flood_freq': 0.76, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Kahalgaon',      'district': 'Bhagalpur',      'state': 'Bihar', 'river': 'Ganga',
      'lat': 25.2167, 'lon': 87.2667,
      'danger_level': 31.09, 'warning_level': 30.00,
      'risk': 'HIGH',  'flood_freq': 0.74, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Bhagalpur',      'district': 'Bhagalpur',      'state': 'Bihar', 'river': 'Ganga',
      'lat': 25.2425, 'lon': 86.9842,
      'danger_level': 33.68, 'warning_level': 32.50,
      'risk': 'HIGH',  'flood_freq': 0.78, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Buxar',          'district': 'Buxar',          'state': 'Bihar', 'river': 'Ganga',
      'lat': 25.5667, 'lon': 83.9667,
      'danger_level': 60.30, 'warning_level': 59.20,
      'risk': 'MODERATE', 'flood_freq': 0.65, 'river_type': 'perennial', 'zone': 'himalayan' },
    // ── BIHAR — Kosi ──────────────────────────────────────────────────────
    { 'city': 'Birpur',         'district': 'Supaul',         'state': 'Bihar', 'river': 'Kosi',
      'lat': 26.5167, 'lon': 86.9000,
      'danger_level': 74.70, 'warning_level': 73.70,
      'risk': 'CRITICAL', 'flood_freq': 0.92, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Baltara',        'district': 'Saharsa',        'state': 'Bihar', 'river': 'Kosi',
      'lat': 25.5000, 'lon': 86.5833,
      'danger_level': 33.85, 'warning_level': 32.85,
      'risk': 'HIGH',  'flood_freq': 0.85, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Basua',          'district': 'Madhubani',      'state': 'Bihar', 'river': 'Kosi',
      'lat': 26.1234, 'lon': 86.6020,
      'danger_level': 47.75, 'warning_level': 46.50,
      'risk': 'HIGH',  'flood_freq': 0.88, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Kursela',        'district': 'Katihar',        'state': 'Bihar', 'river': 'Kosi',
      'lat': 25.4800, 'lon': 87.2600,
      'danger_level': 30.00, 'warning_level': 28.80,
      'risk': 'HIGH',  'flood_freq': 0.82, 'river_type': 'perennial', 'zone': 'himalayan' },
    // ── BIHAR — Gandak ────────────────────────────────────────────────────
    { 'city': 'Chatia',         'district': 'East Champaran', 'state': 'Bihar', 'river': 'Gandak',
      'lat': 26.8500, 'lon': 84.9000,
      'danger_level': 69.15, 'warning_level': 68.10,
      'risk': 'HIGH',  'flood_freq': 0.78, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Dumariaghat',    'district': 'Gopalganj',      'state': 'Bihar', 'river': 'Gandak',
      'lat': 26.4833, 'lon': 84.4667,
      'danger_level': 62.22, 'warning_level': 61.10,
      'risk': 'HIGH',  'flood_freq': 0.80, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Rewaghat',       'district': 'Muzaffarpur',    'state': 'Bihar', 'river': 'Gandak',
      'lat': 26.1000, 'lon': 85.3000,
      'danger_level': 54.41, 'warning_level': 53.40,
      'risk': 'HIGH',  'flood_freq': 0.80, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Hajipur',        'district': 'Vaishali',       'state': 'Bihar', 'river': 'Gandak',
      'lat': 25.6933, 'lon': 85.2094,
      'danger_level': 50.32, 'warning_level': 49.40,
      'risk': 'HIGH',  'flood_freq': 0.76, 'river_type': 'perennial', 'zone': 'himalayan' },
    // ── BIHAR — Bagmati ───────────────────────────────────────────────────
    { 'city': 'Dheng Bridge',   'district': 'Sitamarhi',      'state': 'Bihar', 'river': 'Bagmati',
      'lat': 26.5800, 'lon': 85.4900,
      'danger_level': 71.00, 'warning_level': 70.00,
      'risk': 'HIGH',  'flood_freq': 0.82, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Benibad',        'district': 'Darbhanga',      'state': 'Bihar', 'river': 'Bagmati',
      'lat': 26.0500, 'lon': 85.6500,
      'danger_level': 48.68, 'warning_level': 47.68,
      'risk': 'HIGH',  'flood_freq': 0.80, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Hayaghat',       'district': 'Darbhanga',      'state': 'Bihar', 'river': 'Bagmati',
      'lat': 26.0200, 'lon': 85.9500,
      'danger_level': 45.72, 'warning_level': 44.50,
      'risk': 'HIGH',  'flood_freq': 0.78, 'river_type': 'perennial', 'zone': 'himalayan' },
    // ── BIHAR — Burhi Gandak ──────────────────────────────────────────────
    { 'city': 'Sikandarpur',    'district': 'East Champaran', 'state': 'Bihar', 'river': 'Burhi Gandak',
      'lat': 26.1209, 'lon': 85.3647,
      'danger_level': 52.53, 'warning_level': 51.40,
      'risk': 'HIGH',  'flood_freq': 0.75, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Samastipur',     'district': 'Samastipur',     'state': 'Bihar', 'river': 'Burhi Gandak',
      'lat': 25.8620, 'lon': 85.7812,
      'danger_level': 46.00, 'warning_level': 44.80,
      'risk': 'HIGH',  'flood_freq': 0.73, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Rosera',         'district': 'Samastipur',     'state': 'Bihar', 'river': 'Burhi Gandak',
      'lat': 25.8600, 'lon': 85.9800,
      'danger_level': 42.63, 'warning_level': 41.50,
      'risk': 'MODERATE', 'flood_freq': 0.68, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Khagaria',       'district': 'Khagaria',       'state': 'Bihar', 'river': 'Burhi Gandak',
      'lat': 25.5000, 'lon': 86.4700,
      'danger_level': 36.58, 'warning_level': 35.40,
      'risk': 'HIGH',  'flood_freq': 0.72, 'river_type': 'perennial', 'zone': 'himalayan' },
    // ── BIHAR — Ghaghra ───────────────────────────────────────────────────
    { 'city': 'Darauli',        'district': 'Siwan',          'state': 'Bihar', 'river': 'Ghaghra',
      'lat': 25.9500, 'lon': 84.1500,
      'danger_level': 60.82, 'warning_level': 59.80,
      'risk': 'HIGH',  'flood_freq': 0.70, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Gangpur Siswan', 'district': 'Siwan',          'state': 'Bihar', 'river': 'Ghaghra',
      'lat': 26.0500, 'lon': 84.4000,
      'danger_level': 57.04, 'warning_level': 56.00,
      'risk': 'HIGH',  'flood_freq': 0.68, 'river_type': 'perennial', 'zone': 'himalayan' },
    // ── BIHAR — Mahananda ─────────────────────────────────────────────────
    { 'city': 'Dhengraghat',    'district': 'Kishanganj',     'state': 'Bihar', 'river': 'Mahananda',
      'lat': 25.7800, 'lon': 87.4800,
      'danger_level': 35.65, 'warning_level': 34.65,
      'risk': 'HIGH',  'flood_freq': 0.72, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Taibpur',        'district': 'Araria',         'state': 'Bihar', 'river': 'Mahananda',
      'lat': 26.5800, 'lon': 87.9500,
      'danger_level': 66.00, 'warning_level': 64.80,
      'risk': 'HIGH',  'flood_freq': 0.70, 'river_type': 'perennial', 'zone': 'himalayan' },
    // ── BIHAR — Kamla / Kamalabalan ───────────────────────────────────────
    { 'city': 'Jainagar',       'district': 'Madhubani',      'state': 'Bihar', 'river': 'Kamla',
      'lat': 26.6000, 'lon': 86.2700,
      'danger_level': 67.75, 'warning_level': 66.00,
      'risk': 'HIGH',  'flood_freq': 0.80, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Jhanjharpur',    'district': 'Madhubani',      'state': 'Bihar', 'river': 'Kamalabalan',
      'lat': 26.2700, 'lon': 86.2800,
      'danger_level': 50.00, 'warning_level': 48.80,
      'risk': 'HIGH',  'flood_freq': 0.78, 'river_type': 'perennial', 'zone': 'himalayan' },
    // ── BIHAR — Adhwara ───────────────────────────────────────────────────
    { 'city': 'Sonbarsa',       'district': 'Sitamarhi',      'state': 'Bihar', 'river': 'Adhwara',
      'lat': 26.6500, 'lon': 85.5500,
      'danger_level': 81.85, 'warning_level': 80.70,
      'risk': 'HIGH',  'flood_freq': 0.82, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Kamtaul',        'district': 'Darbhanga',      'state': 'Bihar', 'river': 'Adhwara',
      'lat': 26.2200, 'lon': 85.8500,
      'danger_level': 50.00, 'warning_level': 49.00,
      'risk': 'HIGH',  'flood_freq': 0.80, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Ekmighat',       'district': 'Madhubani',      'state': 'Bihar', 'river': 'Adhwara',
      'lat': 26.1500, 'lon': 86.0000,
      'danger_level': 46.94, 'warning_level': 45.80,
      'risk': 'HIGH',  'flood_freq': 0.78, 'river_type': 'perennial', 'zone': 'himalayan' },
    // ── BIHAR — Punpun ────────────────────────────────────────────────────
    { 'city': 'Sripalpur',      'district': 'Patna',          'state': 'Bihar', 'river': 'Punpun',
      'lat': 25.4833, 'lon': 85.1333,
      'danger_level': 50.60, 'warning_level': 49.50,
      'risk': 'MODERATE', 'flood_freq': 0.55, 'river_type': 'perennial', 'zone': 'himalayan' },
    // ── DELHI ─────────────────────────────────────────────────────────────
    { 'city': 'Delhi',          'district': 'Central Delhi',  'state': 'Delhi', 'river': 'Yamuna',
      'lat': 28.6667, 'lon': 77.2333,
      'danger_level': 205.33, 'warning_level': 204.50,
      'risk': 'HIGH', 'flood_freq': 0.62, 'river_type': 'perennial', 'zone': 'plains',
      'uses_msl': true, 'gauge_name': 'Old Railway Bridge' },
    { 'city': 'Delhi (Palla)',   'district': 'North Delhi',    'state': 'Delhi', 'river': 'Yamuna',
      'lat': 28.8700, 'lon': 77.1100,
      'danger_level': 207.49, 'warning_level': 204.50,
      'risk': 'HIGH', 'flood_freq': 0.58, 'river_type': 'perennial', 'zone': 'plains',
      'uses_msl': true },
    // ── ASSAM ─────────────────────────────────────────────────────────────
    { 'city': 'Guwahati',       'district': 'Kamrup Metro',   'state': 'Assam', 'river': 'Brahmaputra',
      'lat': 26.1445, 'lon': 91.7362,
      'danger_level': 51.68, 'warning_level': 49.68,
      'risk': 'CRITICAL', 'flood_freq': 0.90, 'river_type': 'perennial', 'zone': 'northeast' },
    { 'city': 'Dhubri',         'district': 'Dhubri',         'state': 'Assam', 'river': 'Brahmaputra',
      'lat': 26.0200, 'lon': 89.9700,
      'danger_level': 29.47, 'warning_level': 27.47,
      'risk': 'HIGH', 'flood_freq': 0.85, 'river_type': 'perennial', 'zone': 'northeast' },
    { 'city': 'Goalpara',       'district': 'Goalpara',       'state': 'Assam', 'river': 'Brahmaputra',
      'lat': 26.1800, 'lon': 90.6200,
      'danger_level': 35.15, 'warning_level': 33.15,
      'risk': 'HIGH', 'flood_freq': 0.82, 'river_type': 'perennial', 'zone': 'northeast' },
    { 'city': 'Dibrugarh',      'district': 'Dibrugarh',      'state': 'Assam', 'river': 'Brahmaputra',
      'lat': 27.4728, 'lon': 94.9120,
      'danger_level': 106.45, 'warning_level': 104.45,
      'risk': 'HIGH', 'flood_freq': 0.80, 'river_type': 'perennial', 'zone': 'northeast' },
    // ── WEST BENGAL ───────────────────────────────────────────────────────
    { 'city': 'Farakka',        'district': 'Murshidabad',    'state': 'West Bengal', 'river': 'Ganga',
      'lat': 24.8000, 'lon': 87.9167,
      'danger_level': 25.00, 'warning_level': 23.00,
      'risk': 'HIGH', 'flood_freq': 0.72, 'river_type': 'perennial', 'zone': 'plains' },
    { 'city': 'Murshidabad',    'district': 'Murshidabad',    'state': 'West Bengal', 'river': 'Ganga',
      'lat': 24.1800, 'lon': 88.2700,
      'danger_level': 18.90, 'warning_level': 16.90,
      'risk': 'HIGH', 'flood_freq': 0.68, 'river_type': 'perennial', 'zone': 'plains' },
    { 'city': 'Durgapur Barrage','district': 'Paschim Bardhaman','state': 'West Bengal', 'river': 'Damodar',
      'lat': 23.4889, 'lon': 87.3150,
      'danger_level': 63.00, 'warning_level': 61.00,
      'risk': 'MODERATE', 'flood_freq': 0.60, 'river_type': 'perennial', 'zone': 'plains' },
    // ── UTTAR PRADESH ─────────────────────────────────────────────────────
    { 'city': 'Varanasi',       'district': 'Varanasi',       'state': 'Uttar Pradesh', 'river': 'Ganga',
      'lat': 25.3176, 'lon': 82.9739,
      'danger_level': 71.26, 'warning_level': 70.26,
      'risk': 'HIGH', 'flood_freq': 0.75, 'river_type': 'perennial', 'zone': 'plains' },
    { 'city': 'Prayagraj',      'district': 'Prayagraj',      'state': 'Uttar Pradesh', 'river': 'Ganga',
      'lat': 25.4358, 'lon': 81.8463,
      'danger_level': 84.73, 'warning_level': 83.73,
      'risk': 'HIGH', 'flood_freq': 0.70, 'river_type': 'perennial', 'zone': 'plains' },
    { 'city': 'Ballia',         'district': 'Ballia',         'state': 'Uttar Pradesh', 'river': 'Ganga',
      'lat': 25.7626, 'lon': 84.1479,
      'danger_level': 60.15, 'warning_level': 58.15,
      'risk': 'HIGH', 'flood_freq': 0.72, 'river_type': 'perennial', 'zone': 'plains' },
    { 'city': 'Gorakhpur',      'district': 'Gorakhpur',      'state': 'Uttar Pradesh', 'river': 'Rapti',
      'lat': 26.7606, 'lon': 83.3732,
      'danger_level': 77.37, 'warning_level': 75.37,
      'risk': 'HIGH', 'flood_freq': 0.78, 'river_type': 'perennial', 'zone': 'plains' },
    { 'city': 'Bahraich',       'district': 'Bahraich',       'state': 'Uttar Pradesh', 'river': 'Sharda',
      'lat': 27.5741, 'lon': 81.5953,
      'danger_level': 118.00, 'warning_level': 116.00,
      'risk': 'HIGH', 'flood_freq': 0.74, 'river_type': 'perennial', 'zone': 'plains' },
    // ── ODISHA ────────────────────────────────────────────────────────────
    { 'city': 'Cuttack',        'district': 'Cuttack',        'state': 'Odisha', 'river': 'Mahanadi',
      'lat': 20.4625, 'lon': 85.8828,
      'danger_level': 12.80, 'warning_level': 11.80,
      'risk': 'HIGH', 'flood_freq': 0.80, 'river_type': 'perennial', 'zone': 'coastal' },
    { 'city': 'Kendrapara',     'district': 'Kendrapara',     'state': 'Odisha', 'river': 'Brahmani',
      'lat': 20.5060, 'lon': 86.4230,
      'danger_level': 6.10, 'warning_level': 5.10,
      'risk': 'HIGH', 'flood_freq': 0.76, 'river_type': 'perennial', 'zone': 'coastal' },
    // ── MAHARASHTRA ───────────────────────────────────────────────────────
    { 'city': 'Nashik',         'district': 'Nashik',         'state': 'Maharashtra', 'river': 'Godavari',
      'lat': 19.9975, 'lon': 73.7898,
      'danger_level': 11.50, 'warning_level': 9.50,
      'risk': 'MODERATE', 'flood_freq': 0.55, 'river_type': 'perennial', 'zone': 'coastal' },
    { 'city': 'Nanded',         'district': 'Nanded',         'state': 'Maharashtra', 'river': 'Godavari',
      'lat': 19.1383, 'lon': 77.3210,
      'danger_level': 13.00, 'warning_level': 10.50,
      'risk': 'HIGH', 'flood_freq': 0.62, 'river_type': 'perennial', 'zone': 'coastal' },
    { 'city': 'Sangli',         'district': 'Sangli',         'state': 'Maharashtra', 'river': 'Krishna',
      'lat': 16.8524, 'lon': 74.5815,
      'danger_level': 12.00, 'warning_level': 10.00,
      'risk': 'HIGH', 'flood_freq': 0.65, 'river_type': 'perennial', 'zone': 'coastal' },
    { 'city': 'Kolhapur',       'district': 'Kolhapur',       'state': 'Maharashtra', 'river': 'Panchaganga',
      'lat': 16.7050, 'lon': 74.2433,
      'danger_level': 10.50, 'warning_level': 8.50,
      'risk': 'HIGH', 'flood_freq': 0.68, 'river_type': 'perennial', 'zone': 'coastal' },
    // ── GUJARAT ───────────────────────────────────────────────────────────
    { 'city': 'Ahmedabad',      'district': 'Ahmedabad',      'state': 'Gujarat', 'river': 'Sabarmati',
      'lat': 23.0225, 'lon': 72.5714,
      'danger_level': 48.80, 'warning_level': 46.80,
      'risk': 'MODERATE', 'flood_freq': 0.45, 'river_type': 'perennial', 'zone': 'coastal' },
    { 'city': 'Surat',          'district': 'Surat',          'state': 'Gujarat', 'river': 'Tapi',
      'lat': 21.1702, 'lon': 72.8311,
      'danger_level': 10.00, 'warning_level': 8.50,
      'risk': 'HIGH', 'flood_freq': 0.60, 'river_type': 'perennial', 'zone': 'coastal' },
    // ── ANDHRA PRADESH ────────────────────────────────────────────────────
    { 'city': 'Vijayawada',     'district': 'Krishna',        'state': 'Andhra Pradesh', 'river': 'Krishna',
      'lat': 16.5062, 'lon': 80.6480,
      'danger_level': 12.00, 'warning_level': 10.00,
      'risk': 'HIGH', 'flood_freq': 0.70, 'river_type': 'perennial', 'zone': 'coastal' },
    { 'city': 'Rajahmundry',    'district': 'East Godavari',  'state': 'Andhra Pradesh', 'river': 'Godavari',
      'lat': 17.0005, 'lon': 81.8040,
      'danger_level': 15.00, 'warning_level': 13.00,
      'risk': 'HIGH', 'flood_freq': 0.72, 'river_type': 'perennial', 'zone': 'coastal' },
    // ── KERALA ────────────────────────────────────────────────────────────
    { 'city': 'Alappuzha',      'district': 'Alappuzha',      'state': 'Kerala', 'river': 'Pamba',
      'lat': 9.4981, 'lon': 76.3388,
      'danger_level': 5.00, 'warning_level': 3.50,
      'risk': 'HIGH', 'flood_freq': 0.78, 'river_type': 'perennial', 'zone': 'coastal' },
    { 'city': 'Ernakulam',      'district': 'Ernakulam',      'state': 'Kerala', 'river': 'Periyar',
      'lat': 9.9816, 'lon': 76.2999,
      'danger_level': 7.50, 'warning_level': 6.00,
      'risk': 'MODERATE', 'flood_freq': 0.65, 'river_type': 'perennial', 'zone': 'coastal' },
    // ── TAMIL NADU ────────────────────────────────────────────────────────
    { 'city': 'Tiruchirappalli','district': 'Tiruchirappalli','state': 'Tamil Nadu', 'river': 'Cauvery',
      'lat': 10.7905, 'lon': 78.7047,
      'danger_level': 83.84, 'warning_level': 82.84,
      'risk': 'MODERATE', 'flood_freq': 0.55, 'river_type': 'perennial', 'zone': 'coastal' },
    { 'city': 'Nagapattinam',   'district': 'Nagapattinam',   'state': 'Tamil Nadu', 'river': 'Cauvery',
      'lat': 10.7672, 'lon': 79.8449,
      'danger_level': 2.50, 'warning_level': 1.50,
      'risk': 'HIGH', 'flood_freq': 0.65, 'river_type': 'perennial', 'zone': 'coastal' },
    // ── PUNJAB ────────────────────────────────────────────────────────────
    { 'city': 'Roopnagar',      'district': 'Rupnagar',       'state': 'Punjab', 'river': 'Sutlej',
      'lat': 30.9650, 'lon': 76.5197,
      'danger_level': 285.00, 'warning_level': 283.00,
      'risk': 'HIGH', 'flood_freq': 0.62, 'river_type': 'perennial', 'zone': 'plains' },
    { 'city': 'Ludhiana',       'district': 'Ludhiana',       'state': 'Punjab', 'river': 'Sutlej',
      'lat': 30.9010, 'lon': 75.8573,
      'danger_level': 249.00, 'warning_level': 247.00,
      'risk': 'MODERATE', 'flood_freq': 0.55, 'river_type': 'perennial', 'zone': 'plains' },
    // ── HIMACHAL PRADESH ──────────────────────────────────────────────────
    { 'city': 'Mandi',          'district': 'Mandi',          'state': 'Himachal Pradesh', 'river': 'Beas',
      'lat': 31.7080, 'lon': 76.9318,
      'danger_level': 760.00, 'warning_level': 755.00,
      'risk': 'HIGH', 'flood_freq': 0.70, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Kullu',          'district': 'Kullu',          'state': 'Himachal Pradesh', 'river': 'Beas',
      'lat': 31.9577, 'lon': 77.1095,
      'danger_level': 1195.00, 'warning_level': 1190.00,
      'risk': 'HIGH', 'flood_freq': 0.72, 'river_type': 'perennial', 'zone': 'himalayan' },
    // ── UTTARAKHAND ───────────────────────────────────────────────────────
    { 'city': 'Haridwar',       'district': 'Haridwar',       'state': 'Uttarakhand', 'river': 'Ganga',
      'lat': 29.9457, 'lon': 78.1642,
      'danger_level': 293.50, 'warning_level': 291.50,
      'risk': 'HIGH', 'flood_freq': 0.75, 'river_type': 'perennial', 'zone': 'himalayan' },
    { 'city': 'Dehradun',       'district': 'Dehradun',       'state': 'Uttarakhand', 'river': 'Rispana',
      'lat': 30.3165, 'lon': 78.0322,
      'danger_level': 640.00, 'warning_level': 635.00,
      'risk': 'MODERATE', 'flood_freq': 0.58, 'river_type': 'perennial', 'zone': 'himalayan' },
    // ── MADHYA PRADESH ────────────────────────────────────────────────────
    { 'city': 'Jabalpur',       'district': 'Jabalpur',       'state': 'Madhya Pradesh', 'river': 'Narmada',
      'lat': 23.1815, 'lon': 79.9864,
      'danger_level': 393.00, 'warning_level': 391.00,
      'risk': 'HIGH', 'flood_freq': 0.65, 'river_type': 'perennial', 'zone': 'plains' },
    { 'city': 'Hoshangabad',    'district': 'Narmadapuram',   'state': 'Madhya Pradesh', 'river': 'Narmada',
      'lat': 22.7529, 'lon': 77.7175,
      'danger_level': 290.00, 'warning_level': 288.00,
      'risk': 'HIGH', 'flood_freq': 0.68, 'river_type': 'perennial', 'zone': 'plains' },
    // ── RAJASTHAN ─────────────────────────────────────────────────────────
    { 'city': 'Kota',           'district': 'Kota',           'state': 'Rajasthan', 'river': 'Chambal',
      'lat': 25.2138, 'lon': 75.8648,
      'danger_level': 252.00, 'warning_level': 249.00,
      'risk': 'MODERATE', 'flood_freq': 0.45, 'river_type': 'perennial', 'zone': 'arid' },
    // ── TELANGANA ─────────────────────────────────────────────────────────
    { 'city': 'Hyderabad',      'district': 'Hyderabad',      'state': 'Telangana', 'river': 'Musi',
      'lat': 17.3850, 'lon': 78.4867,
      'danger_level': 7.60, 'warning_level': 6.10,
      'risk': 'MODERATE', 'flood_freq': 0.50, 'river_type': 'seasonal', 'zone': 'plains' },
    { 'city': 'Khammam',        'district': 'Khammam',        'state': 'Telangana', 'river': 'Krishna',
      'lat': 17.2473, 'lon': 80.1514,
      'danger_level': 15.00, 'warning_level': 13.00,
      'risk': 'HIGH', 'flood_freq': 0.68, 'river_type': 'perennial', 'zone': 'plains' },
    // ── KARNATAKA ─────────────────────────────────────────────────────────
    { 'city': 'Raichur',        'district': 'Raichur',        'state': 'Karnataka', 'river': 'Krishna',
      'lat': 16.2120, 'lon': 77.3439,
      'danger_level': 14.00, 'warning_level': 12.00,
      'risk': 'HIGH', 'flood_freq': 0.65, 'river_type': 'perennial', 'zone': 'coastal' },
    { 'city': 'Mysuru',         'district': 'Mysuru',         'state': 'Karnataka', 'river': 'Cauvery',
      'lat': 12.2958, 'lon': 76.6394,
      'danger_level': 760.00, 'warning_level': 758.00,
      'risk': 'MODERATE', 'flood_freq': 0.55, 'river_type': 'perennial', 'zone': 'coastal' },
    // ── HARYANA ───────────────────────────────────────────────────────────
    { 'city': 'Ambala',         'district': 'Ambala',         'state': 'Haryana', 'river': 'Ghaggar',
      'lat': 30.3782, 'lon': 76.7767,
      'danger_level': 262.00, 'warning_level': 260.00,
      'risk': 'HIGH', 'flood_freq': 0.65, 'river_type': 'seasonal', 'zone': 'plains' },
    // ── JHARKHAND ─────────────────────────────────────────────────────────
    { 'city': 'Ranchi',         'district': 'Ranchi',         'state': 'Jharkhand', 'river': 'Subarnarekha',
      'lat': 23.3441, 'lon': 85.3096,
      'danger_level': 10.00, 'warning_level': 8.00,
      'risk': 'MODERATE', 'flood_freq': 0.50, 'river_type': 'perennial', 'zone': 'plains' },
    // ── CHHATTISGARH ──────────────────────────────────────────────────────
    { 'city': 'Raipur',         'district': 'Raipur',         'state': 'Chhattisgarh', 'river': 'Mahanadi',
      'lat': 21.2514, 'lon': 81.6296,
      'danger_level': 265.00, 'warning_level': 263.00,
      'risk': 'MODERATE', 'flood_freq': 0.52, 'river_type': 'perennial', 'zone': 'plains' },
    // ── NORTHEAST ─────────────────────────────────────────────────────────
    { 'city': 'Imphal',         'district': 'Imphal West',    'state': 'Manipur', 'river': 'Manipur River',
      'lat': 24.8170, 'lon': 93.9368,
      'danger_level': 786.00, 'warning_level': 784.00,
      'risk': 'MODERATE', 'flood_freq': 0.55, 'river_type': 'perennial', 'zone': 'northeast' },
    { 'city': 'Agartala',       'district': 'West Tripura',   'state': 'Tripura', 'river': 'Haora',
      'lat': 23.8315, 'lon': 91.2868,
      'danger_level': 13.40, 'warning_level': 11.40,
      'risk': 'HIGH', 'flood_freq': 0.72, 'river_type': 'perennial', 'zone': 'northeast' },
    { 'city': 'Shillong',       'district': 'East Khasi Hills','state': 'Meghalaya', 'river': 'Umiam',
      'lat': 25.5788, 'lon': 91.8933,
      'danger_level': 1496.00, 'warning_level': 1492.00,
      'risk': 'LOW', 'flood_freq': 0.35, 'river_type': 'perennial', 'zone': 'northeast' },
    { 'city': 'Itanagar',       'district': 'Papum Pare',     'state': 'Arunachal Pradesh', 'river': 'Dikrong',
      'lat': 27.0844, 'lon': 93.6053,
      'danger_level': 180.00, 'warning_level': 177.00,
      'risk': 'HIGH', 'flood_freq': 0.75, 'river_type': 'perennial', 'zone': 'himalayan' },
    // ── SIKKIM ────────────────────────────────────────────────────────────
    { 'city': 'Gangtok',        'district': 'East Sikkim',    'state': 'Sikkim', 'river': 'Teesta',
      'lat': 27.3389, 'lon': 88.6065,
      'danger_level': 1600.00, 'warning_level': 1596.00,
      'risk': 'HIGH', 'flood_freq': 0.68, 'river_type': 'perennial', 'zone': 'himalayan' },
    // ── GOA / PUDUCHERRY ──────────────────────────────────────────────────
    { 'city': 'Panaji',         'district': 'North Goa',      'state': 'Goa', 'river': 'Mandovi',
      'lat': 15.4909, 'lon': 73.8278,
      'danger_level': 3.50, 'warning_level': 2.50,
      'risk': 'MODERATE', 'flood_freq': 0.55, 'river_type': 'perennial', 'zone': 'coastal' },
    { 'city': 'Puducherry',     'district': 'Puducherry',     'state': 'Puducherry', 'river': 'Gingee',
      'lat': 11.9416, 'lon': 79.8083,
      'danger_level': 3.00, 'warning_level': 2.00,
      'risk': 'MODERATE', 'flood_freq': 0.50, 'river_type': 'seasonal', 'zone': 'coastal' },
  ];
}
