// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// SECURITY: API keys have been redacted from version control.
/// Run `flutterfire configure` locally to regenerate this file,
/// or set keys via environment variables / CI secrets.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web. '
        'Run flutterfire configure to regenerate.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios. '
          'Run flutterfire configure to regenerate.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos. '
          'Run flutterfire configure to regenerate.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // SECURITY: Replace FIREBASE_API_KEY and FIREBASE_APP_ID with your actual

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCURE2ta3sKTakAy8Cu679h7EdLyFYIuU',
    appId: '1:1071864126219:android:5751e3c0e5e4c59be7e00e',
    messagingSenderId: '1071864126219',
    projectId: 'device-streaming-e762727d',
    storageBucket: 'device-streaming-e762727d.firebasestorage.app',
  );

  // values from the Firebase console. Never commit real keys to git.
}